//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Bases_de_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_MASTER
    {
        public int IdProducto { get; set; }
        public int IdFlujo { get; set; }
        public string TipoProducto { get; set; }
        public string Descripcion { get; set; }
    }
}
